services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - gupta9939

  eurekaserver:
    image: "gupta9939/saloon_eureka_server:v1"
    ports:
      - 8097:8097
    healthcheck:
      test:  "curl --fail --silent http://localhost:8097/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: eurekaserver
    deploy:
      resources:
        limits:
          memory: 824m
    networks:
      - gupta9939

  userdb:
    image: mysql:8.0
    container_name: userdb
    ports:
      - 3301:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: userDatabase
    networks:
      - gupta9939

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - gupta9939

  user:
    image: "gupta9939/saloon_userdetails:v8"
    ports:
      - 8091:8091
    healthcheck:
      test:  "curl --fail --silent http://localhost:8091/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: userservice
    depends_on:
      userdb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "SaloonApointMent"
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/userDatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939

  reviewDb:
    image: mysql:8.0
    container_name: reviewDb
    ports:
      - 3312:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: reviewDatabase
    networks:
      - gupta9939

  review:
    image: "gupta9939/review_service:v1"
    ports:
      - "8098:8098"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8098/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: review_service
    depends_on:
      userdb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "ReviewService"
      SPRING_DATASOURCE_URL: jdbc:mysql://reviewDb:3306/reviewDatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939




  notificationdb:
    image: mysql:8.0
    container_name: notificationdb
    ports:
      - 3309:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: notificationDatabase
    networks:
      - gupta9939



  notification:
    image: "gupta9939/notification_service:v1"
    ports:
      - 8099:8099
    healthcheck:
      test:  "curl --fail --silent http://localhost:8099/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: NotificationServices
    depends_on:
      userdb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "NotificationServices"
      SPRING_DATASOURCE_URL: jdbc:mysql://notificationdb:3306/notificationDatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939




  bookingdb:
    image: mysql:8.0
    container_name: bookingdb
    ports:
      - 3302:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: bookingdatabase
    networks:
      - gupta9939

  booking:
      image: "gupta9939/saloon_booking_service:v3"
      ports:
        - 8095:8095
      healthcheck:
        test: "curl --fail --silent http://localhost:8095/actuator/health | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      container_name: bookingService
      depends_on:
        bookingdb:
          condition: service_healthy
        eurekaserver:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      environment:
        SPRING_APPLICATION_NAME: "BookingService"
        SPRING_DATASOURCE_URL: jdbc:mysql://bookingdb:3306/bookingdatabase?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Ramjik1805
        EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
      deploy:
        resources:
          limits:
            memory: 512m
      networks:
        - gupta9939





  categorydb:
    image: mysql:8.0
    container_name: categorydb
    ports:
      - 3303:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: categorydatabase
    networks:
      - gupta9939

  category:
    image: "gupta9939/saloon_category_service:v3"
    ports:
      - 8093:8093
    healthcheck:
      test: "curl --fail --silent http://localhost:8093/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: categoryService
    depends_on:
      categorydb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "CategoryService"
      SPRING_DATASOURCE_URL: jdbc:mysql://categorydb:3306/categorydatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939







  paymentdb:
    image: mysql:8.0
    container_name: paymentdb
    ports:
      - 3304:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: paymentdatabase
    networks:
      - gupta9939

  payment:
    image: "gupta9939/saloon_payment_service:v3"
    ports:
      - 8096:8096
    healthcheck:
      test: "curl --fail --silent http://localhost:8096/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: paymentService
    depends_on:
      paymentdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "PaymentService"
      SPRING_DATASOURCE_URL: jdbc:mysql://paymentdb:3306/paymentdatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
      RAZORPAY_API_KEY: "rzp_test_lCP0w7Ssj9NhNF"
      RAZORPAY_API_SECRET: "aNNbJVdIHOJpnjpu91FjGOEM"
      STRIPE_API_KEY: "your-stripepay-api-key"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939






  saloonservicedb:
    image: mysql:8.0
    container_name: saloonservicedb
    ports:
      - 3305:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: saloonservicedatabase
    networks:
      - gupta9939

  saloonservice:
    image: "gupta9939/saloon_service_appointment:v3"
    ports:
      - 8092:8092
    healthcheck:
      test: "curl --fail --silent http://localhost:8092/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: saloonservice
    depends_on:
      saloonservicedb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "SaloonServiceAppointment"
      SPRING_DATASOURCE_URL: jdbc:mysql://saloonservicedb:3306/saloonservicedatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939



  offerdb:
    image: mysql:8.0
    container_name: offerdb
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: Ramjik1805
      MYSQL_DATABASE: offerdatabase
    networks:
      - gupta9939

  offerservice:
    image: "gupta9939/saloon_service_offering:v3"
    ports:
      - 8094:8094
    healthcheck:
      test: "curl --fail --silent http://localhost:8094/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: offerservice
    depends_on:
      offerdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "ServiceOffering"
      SPRING_DATASOURCE_URL: jdbc:mysql://offerdb:3306/offerdatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ramjik1805
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939

  gatewayserver:
    image: "gupta9939/saloon_gateway_server:v4"
    ports:
      - 8000:8000
    healthcheck:
      test: "curl --fail --silent http://localhost:8000/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: GateWayServer
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "GateWayServer"
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eurekaserver:8097/eureka/
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - gupta9939

networks:
  gupta9939:
    driver: bridge

volumes:
  keycloak_data:
