spring:
  application:
    name: SaloonApointMent


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/Saloon-Booking-Project/protocol/openid-connect/certs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"